import express, { Application, NextFunction, Request, Response } from "express";
import cors from "cors";
import swaggerUi from "swagger-ui-express";
import openApiSpec from "../openapi.json";
import { RegisterRoutes } from "./generated/routes";

// Note: run `bun run generate` before starting the server.
// tsoa generates `src/generated/routes.ts` and `openapi.json`.

export function createApp(): Application {
  const app = express();

  app.use(express.json());
  app.use(cors());

  // Routes generated by tsoa from controller decorators
  RegisterRoutes(app);

  // Serve the generated OpenAPI spec + Swagger UI
  try {
    app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(openApiSpec));
    app.get("/openapi.json", (_req, res) => res.json(openApiSpec));
  } catch {
    console.warn("openapi.json not found — run `bun run generate` first");
  }

  // Global error handler
  app.use((err: unknown, _req: Request, res: Response, _next: NextFunction) => {
    const status = (err as { status?: number }).status ?? 500;
    const message = err instanceof Error ? err.message : "Unexpected error";
    res.status(status).json({ message });
  });

  return app;
}
